ci: Build and publish container in CI
* Check that container builds on PR
* Publish container from master branch

diff --git a/.github/workflows/pr-ci.yml b/.github/workflows/pr-ci.yml
--- a/.github/workflows/pr-ci.yml
+++ b/.github/workflows/pr-ci.yml
@@ -14,6 +14,21 @@ jobs:
           submodules: recursive
           fetch-depth: 0
 
+      - name: Check if container files was modified and if container version already exists
+        id: checks
+        run: |
+          ./.ci/check-container-sources-modified >> "$GITHUB_OUTPUT"
+          ./.ci/check-container-version-published >> "$GITHUB_OUTPUT"
+
+      - name: Build container image
+        if: steps.checks.outputs.modified == 'true'
+        run: |
+          if "${{ steps.checks.outputs.container-published }}" == "true"; then
+            echo "::error::Container modified but version $(cat .containerversion) already published"
+            exit 1
+          fi
+          ./.ci/build-container
+
       - name: Pull container image
         run: ./.ci/pull-container
 
@@ -65,6 +80,21 @@ jobs:
           git merge --no-ff --no-edit ${{ matrix.commit }}
           echo "merge commit parents:"
           git log -1 --format="Head %H, Parents %P"
+
+      - name: Check if container files was modified and if container version already exists
+        id: checks
+        run: |
+          ./.ci/check-container-sources-modified >> "$GITHUB_OUTPUT"
+          ./.ci/check-container-version-published >> "$GITHUB_OUTPUT"
+
+      - name: Build container image
+        if: steps.checks.outputs.modified == 'true'
+        run: |
+          if "${{ steps.checks.outputs.container-published }}" == "true"; then
+            echo "::error::Container modified but version $(cat .containerversion) already published"
+            exit 1
+          fi
+          ./.ci/build-container
 
       - name: Pull container image
         run: ./.ci/pull-container
